# backend/Dockerfile.e2e

# FROM oven/bun:latest

# WORKDIR /workspace
# COPY . .

# FROM oven/bun:latest
FROM node:slim

# 必要なツールを追加
# procpsはNestJSのホットロードのため
RUN apt-get update && apt-get install -y git curl unzip procps \
        && curl -fsSL https://bun.sh/install | bash

ENV PATH="/root/.bun/bin:$PATH"

WORKDIR /workspace
COPY . .
