# version: '3.9'

services:
  backend-e2e-app:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    env_file:
      - .env.test
    working_dir: /workspace
    depends_on:
      - backend-e2e-db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: >
          sh -c "
            bun install &&
            bunx prisma db push &&
            bun run test:e2e
          "
  backend-e2e-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"